[package]
name = "easy-fs-fuse"
version = "0.1.0"
edition = "2024"

[dependencies]
# clap = { version = "*", features = ["derive"] }
easy-fs = { path = "../easy-fs" }
rand = "*"
toml = { version = "*", features = ["preserve_order"] }
