#!/bin/sh

qemu-system-riscv64 \
    -machine virt \
    -nographic \
    -bios bootloader/rustsbi.bin \
    -device loader,file=target/riscv64gc-unknown-none-elf/release/os.bin,addr=0x80200000 \
    -drive file=target/riscv64gc-unknown-none-elf/release/fs.img,if=none,format=raw,id=x0 \
    -device virtio-blk-device,drive=x0,bus=virtio-mmio-bus.0 \
    -s -S